    create table customer_tbl (
       customer_number integer generated by default as identity,
        address_line1 varchar(255),
        address_line2 varchar(255),
        city varchar(255),
        country varchar(255),
        customer_first_name varchar(255),
        customer_last_name varchar(255),
        phone bigint,
        postal_code integer,
        state varchar(255),
        primary key (customer_number)
    )