    create table order_details_tbl (
       order_number integer generated by default as identity,
        price_each double,
        product_code integer,
        quantity_ordered integer,
        primary key (order_number)
    )